import fs from "fs";
import path from "path";
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFile, cp, mkdir } from "fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";

/* ---------------- helper ---------------- */

async function getObsidianDir() {
  try {
    const env = JSON.parse(await readFile("env.json", "utf8"));
    return env.OBSIDIAN_PLUGIN_DIR;
  } catch {
    return null;
  }
}

function renameCSS() {
  const from = path.resolve("dist/main.css");
  const to = path.resolve("dist/styles.css");
  if (fs.existsSync(from)) {
    fs.renameSync(from, to);
  }
}

/* ---------------- plugins ---------------- */

const copyManifestPlugin = {
  name: "copy-manifest",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0) return;
      if (!fs.existsSync("dist")) await mkdir("dist");
      await cp("manifest.json", "dist/manifest.json");
    });
  },
};

const syncToObsidianPlugin = (obsidianDir) => ({
  name: "sync-to-obsidian",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0 || !obsidianDir) return;

      if (!fs.existsSync(obsidianDir)) {
        await mkdir(obsidianDir, { recursive: true });
      }

      renameCSS();

      const files = [
        ["dist/main.js", "main.js"],
        ["dist/styles.css", "styles.css"],
        ["dist/manifest.json", "manifest.json"],
      ];

      for (const [from, to] of files) {
        const src = path.resolve(from);
        const dest = path.join(obsidianDir, to);
        if (fs.existsSync(src)) {
          await cp(src, dest);
        }
      }

      console.log(`✔ Synced to Obsidian: ${obsidianDir}`);
    });
  },
});

/* ---------------- build ---------------- */

const obsidianDir = await getObsidianDir();

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts", "src/styles.css"],
  bundle: true,
  external: ["obsidian", "electron", ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: "dist",
  minify: prod,

  // No React plugin. No Tailwind/PostCSS plugin.
  // If you import "./styles.css" in your TS, esbuild will still bundle it.
  loader: {
    ".css": "css",
  },

  plugins: [copyManifestPlugin, syncToObsidianPlugin(obsidianDir)],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
