import esbuild from "esbuild";
import builtins from "builtin-modules";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;

const prod = process.argv[2] === "production";
const root = path.resolve(import.meta.dirname)

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: [path.join(root, "src/main.ts")],
  bundle: true,
  external: ["obsidian", "electron", ...builtins],
  format: "cjs",
  target: "es2018",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: "dist",
  minify: prod,
  plugins: [
    {
      name: "ts-build-log",
      setup(build) {
        build.onEnd((result) => {
          if (result.errors.length === 0) {
            console.log("✔ TS bundle built");
          }
        });
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
