import fs from "fs/promises";
import path from "path";
import builtins from "builtin-modules";

export function getTSConfig({ prod, root }) {
  return {
    banner: { js: "/* GENERATED BY ESBUILD */" },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: ["obsidian", "electron", ...builtins],
    format: "cjs",
    target: "es2018",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outdir: "dist",
    absWorkingDir: root,
    minify: prod,
  };
}

export function getStyleConfig({ prod, root }) {
  const HEADER = `/*
GENERATED FILE - DO NOT EDIT styles.css
*/`;

  const annotateCssPlugin = {
    name: "annotate-css",
    setup(build) {
      build.onEnd(async (result) => {
        if (result.errors.length) return;

        const outFile = path.join(root, "dist/styles.css");

        try {
          let css = await fs.readFile(outFile, "utf8");

          // Only add header if OUR header missing
          if (!css.includes("GENERATED FILE - DO NOT EDIT styles.css")) {
            await fs.writeFile(outFile, HEADER + "\n\n" + css);
          }

          console.log("✔ styles.css built");
        } catch {}
      });
    },
  };

  return {
    entryPoints: ["src/styles/index.css"],
    bundle: true,
    outfile: "dist/styles.css",
    absWorkingDir: root,
    sourcemap: prod ? false : true,
    minify: false,
    plugins: [annotateCssPlugin],
  };
}
